"""add conversation agent_kind

Revision ID: 546103fab6c1
Revises: 3895169c7be9
Create Date: 2026-09-15 14:57:17.772544
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "546103fab6c1"
down_revision: str | None = "3895169c7be9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("agent_kind", sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "agent_kind")
    # ### end Alembic commands ###
